AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Template do CloudFormation para criar um sistema de arquivos EFS, dois
  mount targets e uma Launch Configuration para instâncias do Amazon Linux.

Resources:
  # Crie um sistema de arquivos EFS
  MyEFS:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      Encrypted: true
      PerformanceMode: 'generalPurpose'
      ThroughputMode: 'bursting'
      FileSystemTags:
        - Key: Name
          Value: 'MyEFS'

  # Crie o primeiro mount target na Subnet 1
  MountTargetSubnet1:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref MyEFS
      SubnetId: 'SUBNET_ID_1' # Substitua pelo ID da sua subnet
      SecurityGroups:
        - 'SG_ID_DO_EFS' # Substitua pelo ID do seu Security Group
    DependsOn: MyEFS

  # Crie o segundo mount target na Subnet 2
  MountTargetSubnet2:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref MyEFS
      SubnetId: 'SUBNET_ID_2' # Substitua pelo ID da sua subnet
      SecurityGroups:
        - 'SG_ID_DO_EFS' # Substitua pelo ID do seu Security Group
    DependsOn: MyEFS

  # Crie um Security Group para permitir o acesso NFS
  EFSSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group para acesso ao EFS via NFS'
      VpcId: 'VPC_ID' # Substitua pelo ID da sua VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: '0.0.0.0/0' # Recomenda-se restringir a um CIDR mais específico

  # Crie uma Launch Configuration para as instâncias EC2
  MyLaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: 'ami-0abcdef1234567890' # Substitua pela AMI ID do Amazon Linux 2 (ou sua AMI preferida)
      InstanceType: 't2.micro' # Substitua pelo tipo de instância desejado
      SecurityGroups:
        - !Ref MySecurityGroup # Substitua pelo Security Group da sua instância
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          
          # Instala o utilitário nfs-utils (para Amazon Linux 2)
          sudo yum install -y amazon-efs-utils
          
          # Cria o diretório para o ponto de montagem
          sudo mkdir /mnt/efs
          
          # Obtém o ID do EFS
          EFS_ID="${MyEFS}"
          
          # Monta o EFS usando o DNS do mount target
          sudo mount -t efs ${EFS_ID}:/ /mnt/efs
          
          # Opcional: Adiciona a montagem ao /etc/fstab para que seja montado
          # automaticamente no reboot
          echo "${EFS_ID}:/ /mnt/efs efs _netdev,noresvport,tls 0 0" | sudo tee -a /etc/fstab