AWSTemplateFormatVersion: '2010-09-09'
Description: 'Modelo de CloudFormation para testar a criação do EFSMountTarget3'

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id

  PrivateSubnets:
    Description: Subnets to be used
    Type: List<AWS::EC2::Subnet::Id>


  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    Default: 0.0.0.0/0
    MinLength: 9
    MaxLength: 18
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  ### Security Groups
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable NFS access from EC2
      VpcId: !Ref VPC

  ### EFS
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose

  EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    DependsOn: EFSFileSystem
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups:
        - !GetAtt EFSSecurityGroup.GroupId
      SubnetId: !Select
        - 0
        - !Ref PrivateSubnets

  EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    DependsOn: EFSFileSystem
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SecurityGroups:
        - !GetAtt EFSSecurityGroup.GroupId
      SubnetId: !Select
        - 1
        - !Ref PrivateSubnets
