AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Template do CloudFormation para criar um sistema de arquivos EFS, dois
  mount targets e uma Launch Configuration para instâncias do Amazon Linux.

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id

  PrivateSubnets:
    Description: Subnets to be used
    Type: List<AWS::EC2::Subnet::Id>

  EFSSecurityGroup:
    Description: Security Group for EFS
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  EFSFileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      Encrypted: true
      PerformanceMode: 'generalPurpose'
      ThroughputMode: 'bursting'
      FileSystemTags:
        - Key: Name
          Value: 'AWS-Infra-FS'

  MountTargetSubnet1:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Select
        - 0
        - !Ref PrivateSubnets
      SecurityGroups:
        - !Ref EFSSecurityGroup
    DependsOn: EFSFileSystem

  MountTargetSubnet2:
    Type: 'AWS::EFS::MountTarget'
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Select
        - 1
        - !Ref PrivateSubnets
      SecurityGroups:
        - !Ref EFSSecurityGroup
    DependsOn: EFSFileSystem

